### ISSUE TITLE
Add missing codecs

### ISSUE THREAD

**Issue by jaclarke** [jaclarke/__unofficial__edgedb-dart#3]
- [x] `cal::local_date` (#7)
- [x] `cal::local_time` (#7)
- [x] `cal::local_datetime` (#7)
- [x] `cal::relative_duration` (#7)
- [x] `cal::date_duration` (#7)
- [x] `cfg::memory` (https://github.com/edgedb/edgedb-dart/commit/513cc3da4e7be947639183f784f4433f089cea2d)
- [x] `range` (https://github.com/edgedb/edgedb-dart/commit/0410af805fd103e75ad2ef69ca00f964af7e5481)
